#ifndef CPU_ASM_CONFIG_H
#define CPU_ASM_CONFIG_H
#define CPU_MEMORY_ALIGNMENT 32
#define CPU_SSE_COMPLIANT
#define CPU_SSE2_COMPLIANT
#define CPU_SSE41_COMPLIANT
#define CPU_SSE42_COMPLIANT
#define CPU_AVX_COMPLIANT
#define CPU_AVX2_COMPLIANT
#define CPU_POPCNT_COMPLIANT
#define CPU_FMA_COMPLIANT
#define CPU_BMI1_COMPLIANT
#define CPU_BMI2_COMPLIANT
#endif
